#!/bin/bash

#PBS -N ExFftw
#PBS -l walltime=00:03:00
#PBS -l nodes=4:ppn=20
#PBS -q reserved3

module load openmpi/1.8.3/gnu/4.9.2
module load fftw/3.3.4/gnu/4.9.2

cd $PBS_O_WORKDIR

for NPE in 80 #32 40 #1 2 4 8 16 20
do
    for COUNT in 1 2 3 4
    do
	mpirun -np $NPE diffusion.x
    done
done