#!/bin/bash

#PBS -N ExFftw
#PBS -l walltime=00:02:00
#PBS -l nodes=1:ppn=20
#PBS -q reserved3

module load openmpi/1.8.3/gnu/4.9.2
module load fftw/3.3.4/gnu/4.9.2

cd $PBS_O_WORKDIR

mpirun -np 3 diffusion.x